name: Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  wait:
    name: Wait for tests
    runs-on: ubuntu-latest
    steps:
      - name: Wait for tests
        uses: lewagon/wait-on-check-action@v1.3.4
        with:
          ref: ${{ github.ref }}
          check-name: Lint
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Nomad
        uses: datasektionen/nomad-deploy@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          nomad-token: ${{ secrets.NOMAD_TOKEN }}
          nomad-addr: ${{ vars.NOMAD_ADDR }}
